codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 10%
    patch:
      default:
        target: 80%
        threshold: 5%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "cmd/gitbak/main.go"          # Main entry point
  - "build/**/*"                  # Build artifacts
  - "test/**/*"                   # Test files
  - "shell/**/*"                  # Shell script implementation
  - "**/*_test.go"                # Test files (coverage shown in code being tested)
  - ".github/**/*"                # GitHub workflow files
  - "docs/**/*"                   # Documentation
  - "**/*.md"                     # Markdown files
  - "cmd/gitbak/app_test_helpers.go"  # Test helper functions
  - "pkg/git/mocks.go"       # Mock implementations
  - "pkg/git/test_helpers.go"  # Test helper functions
  - "**/*test_helpers.go"         # Any other test helper files